# Site settings

url: "https://www.sacreddata.io"
title: "{ Sacred Data Media Partners }"
description: "Media is our practice. Data is our religion."
keywords: "sacred, data, sacred data, sacred data media partners, media partners, digital media, consulting, media, encoding, video, audio, multimedia"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-68128125-1"
#disqus-shortname: "panossakkos"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Partners: 'partners'
#  Blog: 'blog'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Career variables

events:
  - image: "/img/career/andrew.jpeg"
    date: "Andrew Grathwohl"
    description: "Managing Partner"
  - image: "/img/career/ben.jpg"
    date: "Benjamin Horvath"
    description: "Data Science"
  - image: "/img/career/garrett.jpg"
    date: "Garrett Semmelink"
    description: "Client Relations"
#  - image: "/img/career/phil.jpg"
#    date: "Philip Bernstein"
#    description: "Mobile Applications"
#  - image: "/img/career/brendan.jpg"
#    date: "Brendan Solorz"
#    description: "Content Logistics and Advertising"
#  - image: "/img/career/erwin.jpg"
#    date: "Erwin Perez"
#    description: "Media Production"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Blog variables
#paginate: 15

#paginate_path: "blog/page:num"

#post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/SacredData/"
#  - title: "linkedin"
#    url: "http://no.linkedin.com/in/PanosSakkos"
#  - title: "youtube"
#    url: "http://youtube.com/c/PanosSakkos"
#  - title: "soundcloud"
#    url: "https://soundcloud.com/psakkos/"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
